### ISSUE TITLE
Python Version?

### ISSUE THREAD

**Issue by Unloaded123456** [arek-kwapis/rustedanvil#4]
This project contains Python scripts, and Python language provides only a little backwards compatibility. Which version of Python that used is important when using this project, therefore, information about Python version should be added to prevent "scripts does not work with my Python X.X" issues.

**Comment by arek-kwapis** [comment]
Commit c7e1fcd fixes this.

**Comment by Unloaded123456** [comment]
I have seen the fix commit, that issue has been fixed...
