### ISSUE TITLE
Exes does not support 64 bit

### ISSUE THREAD

**Issue by Unloaded123456** [arek-kwapis/rustedanvil#5]
When I attempt to run exes of RustedAnvil, it does not run and a "unsupported 16-bit app" pop-up appears. What has been went wrong?

**Comment by arek-kwapis** [comment]
Do you by any chance mean the redist files?

**Comment by Unloaded123456** [comment]
Yes, I mean redist files.

**Comment by arek-kwapis** [comment]
In there is the installer for the XAMPP control panel, and the cURL utility that will be used later on for fetching remote content in Milestone 2. XAMPP is the only "real" executable in there. 

Currently, they're unused, as the devtools are built with GOW as a requirement. This will of course change, however since these scripts are just "temporary", I see no need to rework them yet.

**Comment by Unloaded123456** [comment]
I am just randomly running scripts to see if they works and how does they work.

**Comment by Unloaded123456** [comment]
The redist files only contain text data, looks like this:
**curl.exe**
`version https://git-lfs.github.com/spec/v1
oid sha256:491e3231078d817e437ced31480eff54abc6eee0e09e6fa4529e37ce8e8b0cec
size 1731072`
**xampp-windows-x64-8.2.0-0-VS16-installer.exe**
`version https://git-lfs.github.com/spec/v1
oid sha256:06a8bfda66dbe546ecb6ac3afac13a07263f6cb6abbb1d278c994b127e38a4c8
size 155439056`

**Comment by arek-kwapis** [comment]
There might be something wrong with your git install, as it should have pulled the executables from Git LFS during a `git pull` command.

Try installing git LFS by using the `git lfs install` command and pulling the repo again.

You can also always just download them manually. Go into the redist folder, select the file and download from github.

**Comment by Unloaded123456** [comment]
The redist files that I got in this repo was unexecutable files with text data.

**Comment by arek-kwapis** [comment]
Git download: https://git-scm.com/

After you have installed it you can then use the `git` command on your pc and in the Git Bash console, including `git lfs install`

The redist files 100% work. All of Milestone 1's documentation was performed on a different pc. I downloaded XAMPP just fine from the repo, without being logged in

**Comment by Unloaded123456** [comment]
Seems like there is a problem in my side.

**Comment by Unloaded123456** [comment]
Git clones the main branch, how can I clone 1.6.4 - 965 branch with Git?

**Comment by arek-kwapis** [comment]
`git clone -b 1.6.4_965 https://github.com/Abstrat-Technologies/rustedanvil.git`

**Comment by Unloaded123456** [comment]
Oh... Now I do not have the XAMPP exe.

**Comment by Unloaded123456** [comment]
I downloaded it as a file instead of folder, now I have a real executable file.

**Comment by arek-kwapis** [comment]
I looked online and seems to be a known behaviour for when you pull in a repo before having LFS installed. Running `git lfs pull` should restore the pointers back to executable form

**Comment by Unloaded123456** [comment]
Yes, that fixed.

**Comment by Unloaded123456** [comment]
Is curl.exe a stand-alone functional file or is it a tool/library etc. used by any other script?

**Comment by GloryBax** [comment]
> Is curl.exe a stand-alone functional file or is it a tool/library etc. used by any other script?

cURL is a thing we are using for now to download files that are needed by the scripts, and it's called by some of the scripts. 

As far as I have been told, RustedAnvil will be made using NodeJS, and we will probably make our own version of cURL
